In [180]:
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import folium
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
warnings.filterwarnings('ignore')

In [181]:
metros = pd.read_excel('riyadh_metro_stations_Full.xlsx')
cafes = pd.read_excel('riyadh_cafes_and_bakeries.xlsx')

# Show first 5 rows
riyadh_utilites = pd.concat([metros, cafes], axis=0)
riyadh_utilites.head()

,Name,Type_of_Utility,Number_of_Ratings,Rating,Longitude,Latitude
0,Ad Dar Al Baida,Metro Station,8.0,4.9,46.776301,24.559996
1,Ad Dar Al Baida,Metro Station,2.0,5.0,46.776391,24.560102
2,Western Station,Metro Station,1.0,1.0,46.614496,24.581947
3,Western Station,Metro Station,NaN,NaN,46.614811,24.581956
4,Al Aziziah,Metro Station,1.0,4.0,46.760823,24.587257

#EDA

In [182]:
# Show the shape of dataset - # of columns and rows
print('Number of columns and rows: \n')
print(riyadh_utilites.shape)

Number of columns and rows:

(2428, 6)

In [183]:
# Info about the dataset elements
print(riyadh_utilites.info())

<class 'pandas.core.frame.DataFrame'>
Index: 2428 entries, 0 to 2131
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               2428 non-null   object
 1   Type_of_Utility    2428 non-null   object
 2   Number_of_Ratings  2388 non-null   float64
 3   Rating             2388 non-null   float64
 4   Longitude          2428 non-null   float64
 5   Latitude           2428 non-null   float64
dtypes: float64(4), object(2)
memory usage: 132.8+ KB
None

In [184]:
# Description of the dataset
print(riyadh_utilites['Rating'].describe())

count    2388.000000
mean        4.132328
std         0.920038
min         0.000000
25%         4.000000
50%         4.300000
75%         4.600000
max         5.000000
Name: Rating, dtype: float64

In [185]:
# Null values
print(riyadh_utilites.isnull().sum())

Name                  0
Type_of_Utility       0
Number_of_Ratings    40
Rating               40
Longitude             0
Latitude              0
dtype: int64

In [186]:
# Null values - there was no rating for these stations which is fine
riyadh_utilites[riyadh_utilites['Rating'] == 0]

,Name,Type_of_Utility,Number_of_Ratings,Rating,Longitude,Latitude
181,Ministry of Interior,Metro Station,0.0,0.0,46.694914,24.674435
183,Princess Noura University 2,Metro Station,0.0,0.0,46.704561,24.859653
184,Al Hamra,Metro Station,0.0,0.0,46.776660,24.776487
189,King Abdulaziz Hospital,Metro Station,0.0,0.0,46.717623,24.659798
191,Pnu 1,Metro Station,0.0,0.0,46.717416,24.841402
194,Ministry of Finance,Metro Station,0.0,0.0,46.716311,24.652108
195,Al Muorabba,Metro Station,0.0,0.0,46.702307,24.664925
201,Sultanah,Metro Station,0.0,0.0,46.686425,24.614970
202,Pnu 1,Metro Station,0.0,0.0,46.717380,24.841688
209,Western Station,Metro Station,0.0,0.0,46.614811,24.581956
211,Airport T1-2,Metro Station,0.0,0.0,46.699082,24.961015
212,As Sulimaniyah,Metro Station,0.0,0.0,46.700348,24.712787
216,Al Andalus,Metro Station,0.0,0.0,46.790351,24.756780
220,Officers Club,Metro Station,0.0,0.0,46.717875,24.697983
222,King Fahd Library,Metro Station,0.0,0.0,46.686955,24.690287
224,King Salman Oasis,Metro Station,0.0,0.0,46.638607,24.717063
225,Al Margab,Metro Station,0.0,0.0,46.726319,24.634496
229,Al Muorabba,Metro Station,0.0,0.0,46.702289,24.664803
233,Al Hamra,Metro Station,0.0,0.0,46.776687,24.775949
235,STC,Metro Station,0.0,0.0,46.666599,24.726798
236,As Salhiyah,Metro Station,0.0,0.0,46.732975,24.637835
237,Skirinah,Metro Station,0.0,0.0,46.725349,24.617853
238,Hassan Bin Thabit Street,Metro Station,0.0,0.0,46.847456,24.712763
240,Hassan Bin Thabit Street,Metro Station,0.0,0.0,46.847528,24.712746
243,Ishbiliyah,Metro Station,0.0,0.0,46.810940,24.792432
251,Al Jarradiyah,Metro Station,0.0,0.0,46.697411,24.618253
252,Al Owd,Metro Station,0.0,0.0,46.721513,24.625530
257,Railway,Metro Station,0.0,0.0,46.740629,24.649405
263,Riyadh Exhibition Center,Metro Station,0.0,0.0,46.727109,24.754521
267,KACST,Metro Station,0.0,0.0,46.648138,24.721102
272,Al Hamra,Metro Station,0.0,0.0,46.776705,24.776096
273,Khashm Al An,Metro Station,0.0,0.0,46.860311,24.721217
279,Ad Dhabab,Metro Station,0.0,0.0,46.707616,24.709760
280,Ministry of Defence,Metro Station,0.0,0.0,46.718270,24.667994
281,Al Rajhi Grand Mosque,Metro Station,0.0,0.0,46.779454,24.680198
284,Ar Rabi,Metro Station,0.0,0.0,46.660113,24.786217
285,Harun ar Rashid Road,Metro Station,0.0,0.0,46.795992,24.686034
287,Al Rajhi Grand Mosque,Metro Station,0.0,0.0,46.779400,24.680223
288,An Naseem,Metro Station,0.0,0.0,46.827505,24.700521
291,Courts Complex,Metro Station,0.0,0.0,46.712547,24.626910
17,شاهي وكرك مطر ‏وذرة مشوي,cafe,0.0,0.0,46.792268,24.917893
254,بارنز,cafe,0.0,0.0,46.626564,24.954581
257,MALANG CAFE مقهى مالانج,cafe,0.0,0.0,46.810419,24.731430
263,مصنع نمق,cafe,0.0,0.0,46.926407,24.501119
354,Joffreys Coffee&Tea Company,cafe,0.0,0.0,46.622967,24.485535
508,Pret a Manger,cafe,0.0,0.0,46.700921,24.963835
513,خرابة,cafe,0.0,0.0,46.590165,24.572983
546,أستراحة ابو حمد والشلة,cafe,0.0,0.0,46.849659,24.672139
552,بوفيه عارف,cafe,0.0,0.0,46.599629,24.866953
567,قهوة الامل,bakery,0.0,0.0,47.037353,24.566497
574,Chocomelt (Dharat Laban),cafe,0.0,0.0,46.596187,24.632438
640,Baron Filou (Coffee Shop & Fashion),cafe,0.0,0.0,46.652817,24.822904
697,Work area,cafe,0.0,0.0,46.689353,24.976371
737,Bateel el’an,cafe,0.0,0.0,46.702308,24.961130
1074,The Coffee Address | عنوان القهوة,cafe,0.0,0.0,46.767812,24.576313
1311,ويندو كوفي,cafe,0.0,0.0,46.719512,24.860047
1336,Relay,cafe,0.0,0.0,46.700826,24.963667
1433,Caffe Nero,cafe,0.0,0.0,46.700787,24.963717
1443,شاليه كلهم,cafe,0.0,0.0,46.783453,24.908704
1481,Costa Coffee,cafe,0.0,0.0,46.718606,24.859768
1493,Coffee Address,cafe,0.0,0.0,46.874352,24.868997
1557,4Cups Coffee | فوركبز كوفي,cafe,0.0,0.0,46.792264,24.578782
1595,حلى العنود,cafe,0.0,0.0,46.614249,24.572409
1672,Coffee,cafe,0.0,0.0,46.595260,24.474365
1690,Flour + stone,cafe,0.0,0.0,46.708909,24.945494
1711,استراحة عبادي وآخرون,cafe,0.0,0.0,46.798343,24.621112
1764,تبوك🌹,cafe,0.0,0.0,46.642608,25.005785
1798,شاي وفطيرة,cafe,0.0,0.0,46.784526,24.858698
1803,Dunkin' - دانكن,cafe,0.0,0.0,46.705286,24.955642
1814,Bond Cafe,cafe,0.0,0.0,46.804688,24.953312
1862,ديوان ابن حبيجان,cafe,0.0,0.0,46.893644,24.807623
1881,شيخة محمد اللواء,restaurant,0.0,0.0,47.012687,24.959187
1921,Dunkin' - دانكن,cafe,0.0,0.0,46.703985,24.958568
1928,محمد للقهوه والشاي,cafe,0.0,0.0,46.655085,24.863891
1949,شاي عنتلي,cafe,0.0,0.0,46.899808,24.801525
2014,Mr. Bin's Smoking Hub,cafe,0.0,0.0,46.793865,24.951833
2070,Riyadh Hotel,cafe,0.0,0.0,46.974939,24.476689
2115,مزاج المغربي,cafe,0.0,0.0,46.836251,24.568219

In [187]:
# Show available types of Utilities
riyadh_utilites.value_counts('Type_of_Utility')

Type_of_Utility
cafe                 2051
Metro Station         296
bakery                 58
restaurant             13
food                    2
night_club              2
supermarket             2
meal_takeaway           1
gas_station             1
convenience_store       1
point_of_interest       1
Name: count, dtype: int64

# Data Preprocessing

In [188]:
# removal of irrelevant utilities
riyadh_activities = riyadh_utilites[(riyadh_utilites['Type_of_Utility'] == 'cafe') | (riyadh_utilites['Type_of_Utility'] == 'Metro Station')]

In [189]:
# check null values
print(riyadh_activities.isnull().sum())
# check where nulls pertains
riyadh_activities[riyadh_activities['Type_of_Utility'] == 'Metro Station'].isnull().sum() # null values will stay as they are not important for metros

Name                  0
Type_of_Utility       0
Number_of_Ratings    40
Rating               40
Longitude             0
Latitude              0
dtype: int64

Name                  0
Type_of_Utility       0
Number_of_Ratings    40
Rating               40
Longitude             0
Latitude              0
dtype: int64

In [190]:
riyadh_activities['name_coordinates'] = riyadh_activities['Name'] + riyadh_activities['Latitude'].astype(str) + ',' + riyadh_activities['Longitude'].astype(str)

### Information about latitude and longitude:

---

latitude and longitude, in cartography, a coordinate system used to determine and describe the position of any place on Earth’s surface. **Latitude** is a measurement of a location north or south of the Equator. In contrast, **longitude** is a measurement of location east or west

## Map Visualization

In [191]:
# Create a Folium map centered around Riyadh
combined_map = folium.Map(location=[24.7476029,46.8309389 ], zoom_start=15)

# Add markers for cafes (Green icons)
'''
for i in range(0,len(riyadh_activities[(riyadh_activities['Type_of_Utility'] == 'cafe') & (riyadh_activities['Rating']>= 4)])):
    folium.Marker(
        location=[riyadh_activities[(riyadh_activities['Type_of_Utility'] == 'cafe') & (riyadh_activities['Rating'] >= 4)].iloc[i]['Latitude'], riyadh_activities[riyadh_activities['Type_of_Utility'] == 'cafe'].iloc[i]['Longitude']],
        popup=riyadh_activities[riyadh_activities['Type_of_Utility'] == 'cafe'].iloc[i]['Name'],
        icon = folium.Icon(color='green', icon='info-sign') # Ensure correct icon parameters
    ).add_to(combined_map)
'''
# Add markers for metro stations (Blue icons)
for i in range(0,len(riyadh_activities[riyadh_activities['Type_of_Utility'] == 'Metro Station'])):
    folium.Marker(
        location=[riyadh_activities[riyadh_activities['Type_of_Utility'] == 'Metro Station'].iloc[i]['Latitude'], metros.iloc[i]['Longitude']],
        popup=riyadh_activities[riyadh_activities['Type_of_Utility'] == 'Metro Station'].iloc[i]['name_coordinates'],
        icon = folium.Icon(color='blue', icon='info-sign') # Ensure correct icon parameters
    ).add_to(combined_map)

# Add home coordinates

folium.Marker(

 location=[24.7476029,46.8309389],
 popup='Home',
 icon = folium.Icon(color='black', icon='info-sign') # Ensure correct icon parameters
    ).add_to(combined_map)

# Ploygon of U walk
locations = [[24.736184381506888, 46.63128816610638],
             [24.740706763481242, 46.6313090055414],
             [24.74050213831618, 46.626041147565566],
             [24.73727681146874, 46.62577292669105]]
folium.Polygon(
    locations=locations,
    color='red',
    fill=True,
    fill_color='red',
    fill_opacity=0.2,
    tooltip="U walk"
).add_to(combined_map)

In [192]:


# Define the two locations (e.g., London and Paris)
ortangeline_coordinates = [[24.7212165,46.8603114],
                           [24.7127462,46.8475283],
                           [24.705689702065403, 46.83619864582717],
                           [24.7004315,46.8275319],
                           [24.69462201055809, 46.81372388465448],
                           [24.69073260268044, 46.80528030276509],
                           [24.6860343,46.795992],
                           [24.68415283667483, 46.79165754679534],
                           [24.6801982,46.779454],
                           [24.67587181926511, 46.76641951468435],
                           [24.674788373262665, 46.76430976773816],
                           [24.67401966723412, 46.76275749416333],
                           [24.6731455,46.7604457],[24.67248252157945, 46.75864325226789],


                           ]


# Add a blue line connecting London and Paris
folium.PolyLine(locations=[ortangeline_coordinates], color='orange', weight=10, opacity=1).add_to(combined_map)

# Save the map to an HTML file
combined_map